#!/bin/sh

SRCDIR=`dirname $0`;
CLASSES=$@;

# FIXME this should be customizable
n_workers=8;

# copy default configuration file to working directory
test -f ./config || cp ${SRCDIR}/config .;

# copy control scripts to working directory
for cmd in start pause make-new-classes ;
do
  cp ${SRCDIR}/${cmd} .;
  chmod +x ${cmd};
done

# set up input queues
for class in $CLASSES;
do
  for d in IN RUNNING STAGED DONE FAILED log;
  do
    mkdir -p queues/${class}/$d;
  done
done

# set up workers
mkdir workers;
for i in `seq 1 $n_workers`; do
    mkdir workers/$i;
    cp ${SRCDIR}/worker workers/$i/run;
    chmod +x workers/$i/run;
done
