#!/bin/sh

ROOTDIR=`dirname $0`/../.. ;
ROOTDIR=`readlink -f ${ROOTDIR}`;
cd $ROOTDIR;

# read configuration variables, after setting defaults
n_tries=infinite           # Number of tries to attempt to run a job; integer or 'infinite'
start_delay=0              # delay (seconds) before the first attempt to start a job
idle_delay=$((10 * 60))    # delay (seconds) when there are no jobs waiting
restart_delay=$((5 * 60))  # delay (seconds) before restarting a failed job
pause_delay=60             # sleep time while the queue is paused
test -f ./config && { . ./config; }

pause_while_paused() {
  while test -f ${ROOTDIR}/PAUSED ;
  do
    sleep $pause_delay;
  done
}

pause_while_paused ;

lockfile ./lockfile;

ungrabbed_queues=`for q in queues/*; do test -f $q/OWNER || echo $q/IN; done`;

# nothing to do if there are no ungrabbed queues.
test "x$ungrabbed_queues" = "x" && { rm -f ./lockfile ; sleep $idle_delay ; exit 0 ; }

# grab a job; sleep if none found
job_path=`find $ungrabbed_queues -follow -type f | sort --field-separator='/' -k4,4 | head -1`;
if [[ "x${job_path}" != "x" ]]; then
  job_fname=`basename ${job_path}`;
  job_dir=`dirname $job_path`/..;

  owner_file=${job_dir}/OWNER;
  echo $$ > ${owner_file};

  mv $job_path ${job_dir}/RUNNING;
fi

rm -f ./lockfile;

logfile=${job_dir}/log/${job_fname}

## empty job? wait & terminate; else continue
test "x$job_fname" = "x" && { sleep $idle_delay; } || {
    # There's a job ready; run it
    sleep $start_delay;
    while test "$n_tries" != "0"; do
	pause_while_paused ;
	args="";
	test -f ${job_dir}/ARGS && args=`cat ${job_dir}/ARGS`;
	echo "======= Start: `date` ==========" >> $logfile;
	${job_dir}/RUNNING/${job_fname} $args >> $logfile 2>&1 && break;
	sleep $restart_delay;
	test "$n_tries" = "infinite" || n_tries=$((n_tries - 1));
    done

    test "$n_tries" = "0" && { 
       echo "========== FAIL ===========" >> $logfile;
       mv ${job_dir}/RUNNING/${job_fname} ${job_dir}/FAILED;
    } || { 
       echo "======== End: `date` ======" >> $logfile;
       mv ${job_dir}/RUNNING/${job_fname} ${job_dir}/DONE;
    }

    rm ${owner_file};
}
